name: homework_tracker
description: Cross-platform Homework Tracker with offline-first sync and import automation.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sample/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  collection: ^1.18.0
  intl: ^0.19.0
  uuid: ^4.3.3
  sqflite: ^2.3.3
  sqflite_sqlcipher: ^2.2.1
  path: ^1.9.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  supabase_flutter: ^2.3.4
  http: ^1.2.1
  icalendar_parser: ^1.0.1
  csv: ^5.0.2
  html: ^0.15.4
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  workmanager: ^0.5.1
  flutter_local_notifications: ^17.1.2
  go_router: ^13.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  rxdart: ^0.28.0
  logging: ^1.2.0
  dio: ^5.4.3+1
  analyzer: ^6.4.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

